# Generated by Django 4.2.5 on 2024-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
