# Generated by Django 4.2.5 on 2024-09-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
