# Generated by Django 4.2.5 on 2024-09-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_alter_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EADCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EADVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('maintopic', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.eadcities')),
            ],
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
