# Generated by Django 4.2.5 on 2024-09-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0006_lsmcities_lsmvenue_lsmspeakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lsmspeakers',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.lsmcities'),
        ),
    ]
